# Generated by Django 3.1 on 2020-09-04 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournaments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_name', models.CharField(max_length=250)),
                ('lang', models.CharField(max_length=2)),
                ('type', models.CharField(max_length=2)),
                ('date', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Motion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motion_text', models.CharField(max_length=1000)),
                ('info_slide', models.CharField(max_length=9000)),
                ('round', models.CharField(max_length=30)),
                ('tournament_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dir.tournaments')),
            ],
        ),
    ]
