# Generated by Django 3.1 on 2020-09-04 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dir', '0002_auto_20200905_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motion',
            name='info_slide',
            field=models.CharField(blank=True, max_length=9000),
        ),
    ]
