# Generated by Django 3.1 on 2020-09-05 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dir', '0004_auto_20200905_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='date',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
