# Generated by Django 3.1 on 2020-09-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dir', '0006_auto_20200905_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='type',
            field=models.CharField(max_length=3),
        ),
    ]
