# Generated by Django 3.1 on 2020-09-05 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dir', '0007_auto_20200905_1957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='type',
            new_name='format',
        ),
    ]
