# Generated by Django 3.1 on 2020-09-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dir', '0009_auto_20200907_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='lang',
            field=models.CharField(choices=[('bn', 'Bangla'), ('en', 'English')], max_length=2),
        ),
    ]
