# Generated by Django 3.1 on 2020-09-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dir', '0010_auto_20200908_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='format',
            field=models.CharField(choices=[('ap', 'AP'), ('bp', 'BP'), ('3v3', '3v3')], max_length=3),
        ),
    ]
