# Generated by Django 3.1 on 2020-09-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dir', '0012_auto_20200914_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='alt_text',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
